### ISSUE TITLE
input.Type dateInput cannot be empty

### ISSUE THREAD

**Issue by splaisan** [DavidPatShuiFong/DTedit#21] opened 2020-10-15 11:58 UTC
HI,

I did set 5 date fields to `input.types = dateInput` to help the user enter correctly formatted dates but doing so I apparently implied they would be **all** filled by the user during `callback.insert` 

When I leave a date field empty, I get `Error in <-: replacement has length zero`

Is it possible to set the type to dateinput to take advantage of the calendar widget but leave some of the fields empty when creating a record?

Some of these dates are reserved for future edits and cannot be entered today.

Thanks

```
    samplesTable_Results <- DTedit::dtedit(input, output,
                                           name = 'samplesTable',
                                           thedata =  getTable('Samples'),
                                           edit.cols = colnames( getTable('Samples'))[-c(1,2)],
                                           edit.label.cols = colnames( getTable('Samples'))[-c(1,2)],
                                           input.types = c(Type='selectInput', 
                                                           Workflow='selectInput', 
                                                           Species='selectInput', 
                                                           Received='dateInput',
                                                           QC='dateInput',
                                                           Library='dateInput',
                                                           Run='dateInput',
                                                           Analysis='dateInput',
                                                           Comments='textAreaInput'),
                                           input.choices = list(Type=sample_types, 
                                                                Workflow=sample_workflows, 
                                                                Species=sample_species),
                                           view.cols = colnames( getTable('Samples'))[-c(1)],
                                           callback.update = samples.update.callback,
                                           callback.insert = samples.insert.callback,
                                           callback.delete = samples.delete.callback,
                                           icon.delete = shiny::icon("trash"),
                                           icon.edit = shiny::icon("edit"),
                                           icon.add = shiny::icon("plus"),
                                           icon.copy = shiny::icon("copy"),
                                           datatable.options = list(
                                               pageLength = 20,
                                               autoWidth = FALSE,
                                               dom = 'Bfrtip',
                                               columnDefs = list(list(className = 'dt-left', targets = "_all"))
                                               )
                                           )
```

**Comment by DavidPatShuiFong** [comment] 2020-10-21 09:51
Reproducible example

```r
library(shiny)
library(DTedit)

server <- function(input, output) {
    
    grocery.update.callback <- function(data, olddata, row) {
        # 'data' contains the dataframe *after* the row has been updated
        # 'row' is the row number where data has been updated
        # 'olddata' is the previous version of the data
        browser()

        return(data)
    }
    
    grocery.insert.callback <- function(data, row) {
        # 'data' contains the dataframe *after* the row has been inserted
        
        msg <- list()
        if (data[row, "Buy"] == "") {
            msg[[1]] <- "Item name can't be empty!"
        }
        msg <- Filter(Negate(is.null), msg)
        if (length(msg)) stop(paste(msg, collapse = "<br>"))
        
        return(data)
    }
    
    Grocery_List_Results <- dtedit(
        input, output,
        name = 'Grocery_List',
        thedata = data.frame(
            Buy = c('Tea', 'Biscuits', 'Apples'),
            Logged = c(as.Date("2020-05-04"), as.Date("2020-07-08"), as.Date("2020-09-05")),
            Completed = c(as.Date("2020-08-07"), as.Date(NA), as.Date("2020-10-07")),
            stringsAsFactors = FALSE
        ),
        callback.update = grocery.update.callback,
        callback.insert = grocery.insert.callback
    )
    
    observeEvent(Grocery_List_Results$thedata, {
        message(Grocery_List_Results$thedata)
    })
    
}

ui <- fluidPage(
    h3('Grocery List'),
    uiOutput('Grocery_List')
)

shinyApp(ui = ui, server = server)
```

* Able to create *new* data row with `NA` (empty) dates
* Unable to edit *old* data row, changing current 'filled' date to a `NA` (empty) date

 Problem in code `dtedit.R`, currently lines 976 to 995

```r
      for (i in edit.cols) {
        if (inputTypes[i] %in% c("selectInputMultiple",
                                 "selectInputMultipleReactive")) {
          newdata[[i]][row] <- list(input[[paste0(name, "_edit_", i)]])
        } else if (inputTypes[i] == "fileInput") {
          datapath <- input[[paste0(name, "_edit_", i)]]$datapath
          if (!is.null(datapath) && file.exists(datapath)) {
            # only if file actually uploaded, otherwise we won't update
            newdata[[i]][row] <- blob::blob(
              readBin( # file read into binary raw (blob) column
                datapath,
                what = "raw",
                n = max.fileInputLength
              )
            )
          }
        } else {
          newdata[row, i] <- input[[paste0(name, "_edit_", i)]]
        }
      }
```

`input[[ab_edit_Completed]]` returns a data of length 0 if the entry is left blank.
This doesn't matter when creating a new row, since the default is `NA`.

However, with editing an old row, the `newdata[row, i] <-` fails to replace the old date.

**Comment by DavidPatShuiFong** [comment] 2020-10-21 10:10
I think this fixes the issue. It is now in the 'develop' branch.

**Comment by splaisan** [comment] 2020-10-22 12:27
thanks a lot David, I try this asap

**Comment by DavidPatShuiFong** [comment] 2020-11-01 10:55
I'm assuming testing is okay, and closing this issue now

**Closed by DavidPatShuiFong** 2020-11-01 10:55 UTC
Labels: bug

**Comment by splaisan** [comment] 2020-11-02 10:26
Thanks David,

Yes it now allows to save a record with an empty date but the saved date is weird '18568' and looks too short to be a correct timestamp.
Is it possible to pick a date and have it saved in format yyyy-mm-dd instead of now '18568' which does not fit for '2020-11-02' as from `Sys.Date()`?

I include here a demo based on your own

Thanks

```
library(shiny)
# devtools::install_github('DavidPatShuiFong/DTedit', ref="develop") - v2.2.4
library(DTedit)

##### Create the Shiny server
server <- function(input, output) {
    mydata <- data.frame(text = character(),
                         date = character(),
                         stringsAsFactors = FALSE)
    
    ##### Callback functions.
    my.insert.callback <- function(data, row) {
        # 'data' contains the dataframe *after* the row has been inserted/added
        # 'row' is the row number where data has been inserted
        mydata <<- rbind(mydata, data[row,])
        # in this case, 'mydata' should just be the same as 'data'
        return(mydata)
    }
    
    my.update.callback <- function(data, olddata, row) {
        # 'data' contains the dataframe *after* the row has been updated
        # 'row' is the row number where data has been updated
        # 'olddata' is the previous version of the data
        mydata[row,] <<- data[row,]
        # in this case, 'mydata' should just be the same as 'data'
        return(mydata)
    }
    
    my.delete.callback <- function(data, row) {
        # 'data' contains the dataframe *before* the row has been deleted
        # 'row' is the row number where data is to be deleted
        mydata <<- mydata[-row,]
        # in this case, 'mydata' should just be the same as data[-c(row),]
        return(mydata)
    }
    
    ##### Create the DTedit object
    DTedit::dtedit(
        input, output,
        name = 'mycontacts',
        thedata = mydata,
        edit.cols = c('text', 'date'),
        edit.label.cols = c('Text', 'date'),
        input.types = c(text = 'textAreaInput',
                        date =  'dateInput'),
        view.cols = c('text', 'date'),
        callback.update = my.update.callback,
        callback.insert = my.insert.callback,
        callback.delete = my.delete.callback)
}

##### Create the shiny UI
ui <- fluidPage(
    h3('DTedit Template'),
    uiOutput('mycontacts')
)

##### Start the shiny app
shinyApp(ui = ui, server = server)
```

**Comment by DavidPatShuiFong** [comment] 2020-11-02 11:05
`Date` datatypes are based on `numeric`, not `character`.

Replace the initial dataframe definition with

```r
mydata <- data.frame(
  text = character(),
  date = as.Date(numeric()),
  stringsAsFactors = FALSE
)
```

**Comment by splaisan** [comment] 2020-11-02 11:07
my bad :-) thanks David, now works like a charm
have a great day!
